from datetime import date, time

from .connection import SessionLocal
from .models import (
    User,
    Stock,
    StockEvent,
    Center,
    Vehicule,
    VehiculeDocument,
    CenterSchedule,
    ClosingPeriod,
    Inventory,
    InventoryStock,
)
from app.enums import (
    VehiculeCategory,
    VehiculeStatus,
    UserStatus,
    CenterStatus,
    WeekDays,
    StockStatus,
    StockCategory,
    InventoryStatus,
    InventoryStockStatus,
)
from app.enums.stock_event_type_enum import StockEventType

# crypt context for password hashing
import bcrypt


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def seed():
    db = SessionLocal()

    # Vérifie que les users n'existent pas déjà
    if db.query(User).first():
        print("DB déjà seedée, skip")
        db.close()
        return

    users = [
        User(
            name="Antoine",
            lastname="Lefebvre",
            email="superadmin@resto.com",
            password=hash_password("1234"),
            photo_url="/uploads/avatars/user_1.png",
            center_id=1,
            status=UserStatus.SUPER_ADMIN,
            telephone="0123456789",
            street="17 Rue Saint-Aspais",
            city="Melun",
            postal_code="77000",
            created_at=date(2026, 1, 1),
            updated_at=date(2026, 1, 1),
        ),
        User(
            name="Julie",
            lastname="Moreau",
            email="admin@resto.com",
            password=hash_password("1234"),
            photo_url="/uploads/avatars/user_2.png",
            center_id=1,
            status=UserStatus.ADMIN,
            telephone="0123456789",
            street="3 Rue de la Préfecture",
            city="Melun",
            postal_code="77000",
            created_at=date(2026, 1, 5),
            updated_at=date(2026, 1, 5),
        ),
        User(
            name="Marc",
            lastname="Dubois",
            email="resp1@resto.com",
            password=hash_password("1234"),
            photo_url="/uploads/avatars/user_3.png",
            center_id=1,
            status=UserStatus.CENTER_ADMIN,
            telephone="0123456789",
            street="17 Rue Saint-Aspais",
            city="Melun",
            postal_code="77000",
            created_at=date(2026, 2, 1),
            updated_at=date(2026, 2, 1),
        ),
        User(
            name="Sophie",
            lastname="Bernard",
            email="resp2@resto.com",
            password=hash_password("1234"),
            photo_url="/uploads/avatars/user_4.png",
            center_id=2,
            status=UserStatus.CENTER_ADMIN,
            telephone="0123456789",
            street="42 Rue du Général Leclerc",
            city="Meaux",
            postal_code="77100",
            created_at=date(2026, 2, 5),
            updated_at=date(2026, 2, 5),
        ),
        User(
            name="Karim",
            lastname="Benali",
            email="vehicule1@resto.com",
            password=hash_password("1234"),
            photo_url="/uploads/avatars/user_5.png",
            center_id=1,
            status=UserStatus.VEHICULE_ADMIN,
            telephone="0123456789",
            street="9 Avenue Thiers",
            city="Melun",
            postal_code="77000",
            created_at=date(2026, 3, 1),
            updated_at=date(2026, 3, 1),
        ),
        User(
            name="Léa",
            lastname="Girard",
            email="vehicule2@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=2,
            status=UserStatus.VEHICULE_ADMIN,
            telephone="0123456789",
            street="12 Rue Saint-Rémy",
            city="Meaux",
            postal_code="77100",
            created_at=date(2026, 3, 5),
            updated_at=date(2026, 3, 5),
        ),
        User(
            name="Hugo",
            lastname="Petit",
            email="stock1@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=1,
            status=UserStatus.STOCK_ADMIN,
            telephone="0123456789",
            street="25 Rue du Miroir",
            city="Melun",
            postal_code="77000",
            created_at=date(2026, 3, 10),
            updated_at=date(2026, 3, 10),
        ),
        User(
            name="Nina",
            lastname="Roux",
            email="stock2@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=2,
            status=UserStatus.STOCK_ADMIN,
            telephone="0123456789",
            street="8 Rue du Marché",
            city="Meaux",
            postal_code="77100",
            created_at=date(2026, 4, 1),
            updated_at=date(2026, 4, 1),
        ),
        User(
            name="Paul",
            lastname="Fontaine",
            email="user@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=1,
            status=UserStatus.User,
            telephone="0123456789",
            street="4 Rue du Château",
            city="Melun",
            postal_code="77000",
            created_at=date(2026, 4, 5),
            updated_at=date(2026, 4, 5),
        ),
        User(
            name="Emma",
            lastname="Chevalier",
            email="user2@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=2,
            status=UserStatus.User,
            telephone="0123456789",
            street="18 Rue de la Gare",
            city="Meaux",
            postal_code="77100",
            created_at=date(2026, 5, 1),
            updated_at=date(2026, 5, 1),
        ),
        User(
            name="Thomas",
            lastname="Girard",
            email="resp3@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=3,
            status=UserStatus.CENTER_ADMIN,
            telephone="0123456789",
            street="8 Avenue de la Résistance",
            city="Chelles",
            postal_code="77500",
            created_at=date(2026, 5, 5),
            updated_at=date(2026, 5, 5),
        ),
        User(
            name="Camille",
            lastname="Lambert",
            email="resp4@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=4,
            status=UserStatus.CENTER_ADMIN,
            telephone="0123456789",
            street="23 Avenue Charles Rouxel",
            city="Pontault-Combault",
            postal_code="77340",
            created_at=date(2026, 5, 10),
            updated_at=date(2026, 5, 10),
        ),
        User(
            name="Yanis",
            lastname="Da Silva",
            email="resp5@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=5,
            status=UserStatus.CENTER_ADMIN,
            telephone="0123456789",
            street="5 Rue Grande",
            city="Fontainebleau",
            postal_code="77300",
            created_at=date(2026, 5, 15),
            updated_at=date(2026, 5, 15),
        ),
        User(
            name="Chloé",
            lastname="Perrin",
            email="resp6@resto.com",
            password=hash_password("1234"),
            photo_url=None,
            center_id=6,
            status=UserStatus.CENTER_ADMIN,
            telephone="0123456789",
            street="15 Rue de Paris",
            city="Torcy",
            postal_code="77200",
            created_at=date(2026, 5, 20),
            updated_at=date(2026, 5, 20),
        ),
    ]

    stocks = [
        Stock(
            reference="REF001_c1",
            name="Pc",
            category=StockCategory.INFORMATIQUE,
            status=StockStatus.LOST,
            qr_code="REF001_c1",
            creation_date=date(2025, 1, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=1,
        ),
        Stock(
            reference="REF002_c1",
            name="Frigo",
            category=StockCategory.REFRIGIRE,
            status=StockStatus.AVAILABLE,
            qr_code="REF002_c1",
            creation_date=date(2025, 6, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=1,
        ),
        Stock(
            reference="REF001_c2",
            name="Pc",
            category=StockCategory.INFORMATIQUE,
            status=StockStatus.LOST,
            qr_code="REF001_c2",
            creation_date=date(2025, 1, 1),
            last_scan_date=date(2026, 3, 1),
            center_id=2,
        ),
        Stock(
            reference="REF002_c2",
            name="Frigo",
            category=StockCategory.REFRIGIRE,
            status=StockStatus.AVAILABLE,
            qr_code="REF002_c2",
            creation_date=date(2025, 9, 1),
            last_scan_date=date(2026, 4, 1),
            center_id=2,
        ),
        Stock(
            reference="REF003_c2",
            name="Table",
            category=StockCategory.BUREAU,
            status=StockStatus.AVAILABLE,
            qr_code="REF003_c2",
            creation_date=date(2025, 1, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=2,
        ),
        Stock(
            reference="REF003_c1",
            name="Imprimante",
            category=StockCategory.INFORMATIQUE,
            status=StockStatus.AVAILABLE,
            qr_code="REF003_c1",
            creation_date=date(2025, 3, 15),
            last_scan_date=date(2026, 6, 1),
            center_id=1,
        ),
        Stock(
            reference="REF004_c1",
            name="Four",
            category=StockCategory.RESTAURATION,
            status=StockStatus.AVAILABLE,
            qr_code="REF004_c1",
            creation_date=date(2025, 4, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=1,
        ),
        Stock(
            reference="REF005_c1",
            name="Chaise",
            category=StockCategory.BUREAU,
            status=StockStatus.LOST,
            qr_code="REF005_c1",
            creation_date=date(2025, 5, 1),
            last_scan_date=date(2026, 2, 1),
            center_id=1,
        ),
        Stock(
            reference="REF004_c2",
            name="Congélateur",
            category=StockCategory.REFRIGIRE,
            status=StockStatus.AVAILABLE,
            qr_code="REF004_c2",
            creation_date=date(2025, 6, 1),
            last_scan_date=date(2026, 5, 1),
            center_id=2,
        ),
        Stock(
            reference="REF005_c2",
            name="Écran",
            category=StockCategory.INFORMATIQUE,
            status=StockStatus.AVAILABLE,
            qr_code="REF005_c2",
            creation_date=date(2025, 7, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=2,
        ),
        Stock(
            reference="REF001_c3",
            name="Pc",
            category=StockCategory.INFORMATIQUE,
            status=StockStatus.AVAILABLE,
            qr_code="REF001_c3",
            creation_date=date(2025, 8, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=3,
        ),
        Stock(
            reference="REF001_c4",
            name="Frigo",
            category=StockCategory.REFRIGIRE,
            status=StockStatus.AVAILABLE,
            qr_code="REF001_c4",
            creation_date=date(2025, 9, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=4,
        ),
        Stock(
            reference="REF001_c5",
            name="Table",
            category=StockCategory.BUREAU,
            status=StockStatus.AVAILABLE,
            qr_code="REF001_c5",
            creation_date=date(2025, 10, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=5,
        ),
        Stock(
            reference="REF001_c6",
            name="Chariot",
            category=StockCategory.OTHER,
            status=StockStatus.AVAILABLE,
            qr_code="REF001_c6",
            creation_date=date(2025, 11, 1),
            last_scan_date=date(2026, 6, 1),
            center_id=6,
        ),
    ]

    centers = [
        Center(
            name="Centre Melun",
            street_number=17,
            street="Rue Saint-Aspais",
            city="Melun",
            postal_code="77000",
            telephone="01 64 00 11 22",
            email="melun@restosducoeur.org",
            status=CenterStatus.OPEN,
            description="Centre principal situé au cœur de la préfecture de Seine-et-Marne.",
            activities="Restauration rapide, livraison",
        ),
        Center(
            name="Centre Meaux",
            street_number=42,
            street="Rue du Général Leclerc",
            city="Meaux",
            postal_code="77100",
            telephone="01 64 00 22 33",
            email="meaux@restosducoeur.org",
            status=CenterStatus.OPEN,
            description="Centre situé dans le nord de la Seine-et-Marne.",
            activities="Restauration sur place, traiteur",
        ),
        Center(
            name="Centre Chelles",
            street_number=8,
            street="Avenue de la Résistance",
            city="Chelles",
            postal_code="77500",
            telephone="01 64 00 33 44",
            email="chelles@restosducoeur.org",
            status=CenterStatus.TEMPORARY_CLOSE,
            description="Centre fermé temporairement pour travaux.",
            activities="Restauration rapide",
        ),
        Center(
            name="Centre Pontault-Combault",
            street_number=23,
            street="Avenue Charles Rouxel",
            city="Pontault-Combault",
            postal_code="77340",
            telephone="01 64 00 44 55",
            email="pontault@restosducoeur.org",
            status=CenterStatus.OPEN,
            description="Centre desservant le secteur est de l'agglomération.",
            activities="Livraison, traiteur événementiel",
        ),
        Center(
            name="Centre Fontainebleau",
            street_number=5,
            street="Rue Grande",
            city="Fontainebleau",
            postal_code="77300",
            telephone="01 64 00 55 66",
            email="fontainebleau@restosducoeur.org",
            status=CenterStatus.CLOSE,
            description="Centre actuellement fermé.",
            activities="Restauration rapide",
        ),
        Center(
            name="Entrepôt Torcy",
            street_number=15,
            street="Rue de Paris",
            city="Torcy",
            postal_code="77200",
            status=CenterStatus.OPEN,
            description="Entrepôt situé dans le secteur de Marne-la-Vallée.",
            activities="Stockage, livraison",
            is_warehouse=True,
        ),
    ]

    center_schedules = [
        # Centre 1
        CenterSchedule(
            center_id=1,
            day_of_week=WeekDays.MONDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 0),
        ),
        CenterSchedule(
            center_id=1,
            day_of_week=WeekDays.TUESDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 0),
        ),
        CenterSchedule(
            center_id=1,
            day_of_week=WeekDays.WEDNESDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 0),
        ),
        CenterSchedule(
            center_id=1,
            day_of_week=WeekDays.THURSDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 0),
        ),
        CenterSchedule(
            center_id=1,
            day_of_week=WeekDays.FRIDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 0),
        ),
        CenterSchedule(
            center_id=1,
            day_of_week=WeekDays.SATURDAY,
            opening_time=time(10, 0),
            closing_time=time(17, 0),
        ),
        # Centre 2
        CenterSchedule(
            center_id=2,
            day_of_week=WeekDays.MONDAY,
            opening_time=time(8, 30),
            closing_time=time(18, 30),
        ),
        CenterSchedule(
            center_id=2,
            day_of_week=WeekDays.TUESDAY,
            opening_time=time(8, 30),
            closing_time=time(18, 30),
        ),
        CenterSchedule(
            center_id=2,
            day_of_week=WeekDays.WEDNESDAY,
            opening_time=time(8, 30),
            closing_time=time(18, 30),
        ),
        CenterSchedule(
            center_id=2,
            day_of_week=WeekDays.THURSDAY,
            opening_time=time(8, 30),
            closing_time=time(18, 30),
        ),
        CenterSchedule(
            center_id=2,
            day_of_week=WeekDays.FRIDAY,
            opening_time=time(8, 30),
            closing_time=time(18, 30),
        ),
        CenterSchedule(
            center_id=2,
            day_of_week=WeekDays.SATURDAY,
            opening_time=time(9, 0),
            closing_time=time(16, 0),
        ),
        # Centre 3 (fermé temporairement, mais on garde des horaires de référence)
        CenterSchedule(
            center_id=3,
            day_of_week=WeekDays.MONDAY,
            opening_time=time(9, 0),
            closing_time=time(18, 0),
        ),
        CenterSchedule(
            center_id=3,
            day_of_week=WeekDays.TUESDAY,
            opening_time=time(9, 0),
            closing_time=time(18, 0),
        ),
        CenterSchedule(
            center_id=3,
            day_of_week=WeekDays.WEDNESDAY,
            opening_time=time(9, 0),
            closing_time=time(18, 0),
        ),
        CenterSchedule(
            center_id=3,
            day_of_week=WeekDays.THURSDAY,
            opening_time=time(9, 0),
            closing_time=time(18, 0),
        ),
        CenterSchedule(
            center_id=3,
            day_of_week=WeekDays.FRIDAY,
            opening_time=time(9, 0),
            closing_time=time(18, 0),
        ),
        # Centre 4
        CenterSchedule(
            center_id=4,
            day_of_week=WeekDays.MONDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 30),
        ),
        CenterSchedule(
            center_id=4,
            day_of_week=WeekDays.TUESDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 30),
        ),
        CenterSchedule(
            center_id=4,
            day_of_week=WeekDays.WEDNESDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 30),
        ),
        CenterSchedule(
            center_id=4,
            day_of_week=WeekDays.THURSDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 30),
        ),
        CenterSchedule(
            center_id=4,
            day_of_week=WeekDays.FRIDAY,
            opening_time=time(9, 0),
            closing_time=time(19, 30),
        ),
        CenterSchedule(
            center_id=4,
            day_of_week=WeekDays.SATURDAY,
            opening_time=time(10, 0),
            closing_time=time(18, 0),
        ),
        # Centre 5 (fermé, pas d'horaires actuels)
    ]

    vehicules = [
        Vehicule(
            name="Véhicule 1",
            immatriculation="AA-123-AA",
            category=VehiculeCategory.VOITURE,
            status=VehiculeStatus.IN_SERVICE,
            nb_km=120000,
            last_technical_inspection_date=date(2025, 6, 1),
            next_technical_inspection_date=date(2026, 6, 1),
            last_service_date=date(2025, 3, 10),
            next_service_date=date(2025, 9, 10),
            center_id=1,
            user_id=3,
        ),
        Vehicule(
            name="Véhicule 2",
            immatriculation="BB-456-BB",
            category=VehiculeCategory.CAMION,
            status=VehiculeStatus.IN_MAINTENANCE,
            nb_km=150000,
            last_technical_inspection_date=date(2025, 6, 1),
            next_technical_inspection_date=date(2026, 6, 1),
            last_service_date=date(2025, 3, 10),
            next_service_date=date(2025, 9, 10),
            center_id=1,
            user_id=5,
        ),
        Vehicule(
            name="Véhicule 3",
            immatriculation="CC-789-CC",
            category=VehiculeCategory.VOITURE,
            status=VehiculeStatus.IN_SERVICE,
            nb_km=90000,
            last_technical_inspection_date=date(2025, 6, 1),
            next_technical_inspection_date=date(2026, 6, 1),
            last_service_date=date(2025, 3, 10),
            next_service_date=date(2025, 9, 10),
            center_id=2,
            user_id=4,
        ),
        Vehicule(
            name="Véhicule 4",
            immatriculation="DD-012-DD",
            category=VehiculeCategory.UTILITAIRE,
            status=VehiculeStatus.OUT_OF_SERVICE,
            nb_km=200000,
            last_technical_inspection_date=date(2025, 6, 1),
            next_technical_inspection_date=date(2026, 6, 1),
            last_service_date=date(2025, 3, 10),
            next_service_date=date(2025, 9, 10),
            center_id=2,
            user_id=None,
        ),
        Vehicule(
            name="Véhicule 5",
            immatriculation="EE-345-EE",
            category=VehiculeCategory.FOURGON,
            status=VehiculeStatus.UNDER_REPAIR,
            nb_km=10000,
            last_technical_inspection_date=date(2025, 6, 1),
            next_technical_inspection_date=date(2026, 6, 1),
            last_service_date=date(2025, 3, 10),
            next_service_date=date(2025, 9, 10),
            center_id=1,
            user_id=None,
        ),
    ]

    vehicule_documents = [
        VehiculeDocument(
            file_name="document1.pdf",
            description="Contrôle technique",
            upload_date=date(2026, 1, 5),
            file_date=date(2026, 1, 5),
            expiration_date=date(2027, 1, 5),
            file_url="/uploads/vehicule_documents/document1.pdf",
            vehicule_id=1,
        ),
        VehiculeDocument(
            file_name="document2.pdf",
            description="Assurance",
            upload_date=date(2026, 2, 10),
            file_date=date(2026, 2, 10),
            expiration_date=date(2027, 2, 10),
            file_url="/uploads/vehicule_documents/document2.pdf",
            vehicule_id=1,
        ),
        VehiculeDocument(
            file_name="document3.pdf",
            description="Contrôle technique",
            upload_date=date(2026, 3, 14),
            file_date=date(2026, 3, 14),
            expiration_date=date(2027, 3, 14),
            file_url="/uploads/vehicule_documents/document3.pdf",
            vehicule_id=2,
        ),
        VehiculeDocument(
            file_name="document4.pdf",
            description="Assurance",
            upload_date=date(2026, 4, 2),
            file_date=date(2026, 4, 2),
            expiration_date=date(2027, 4, 2),
            file_url="/uploads/vehicule_documents/document4.pdf",
            vehicule_id=3,
        ),
        VehiculeDocument(
            file_name="document5.pdf",
            description="Document ATP",
            upload_date=date(2026, 5, 9),
            file_date=date(2026, 5, 9),
            expiration_date=date(2027, 5, 9),
            file_url="/uploads/vehicule_documents/document5.pdf",
            vehicule_id=5,
        ),
    ]

    closing_periods = [
        ClosingPeriod(
            center_id=1, start_date=date(2026, 7, 13), end_date=date(2026, 7, 30)
        ),
        ClosingPeriod(
            center_id=1, start_date=date(2026, 8, 10), end_date=date(2026, 8, 23)
        ),
        ClosingPeriod(
            center_id=2, start_date=date(2026, 7, 20), end_date=date(2026, 8, 15)
        ),
    ]

    inventories = [
        Inventory(
            inventory_start_date=date(2026, 6, 15),
            inventory_end_date=date(2026, 6, 15),
            status=InventoryStatus.FINISHED,
            center_id=1,
            user_id=3,
        ),
        Inventory(
            inventory_start_date=date(2026, 7, 1),
            inventory_end_date=None,
            status=InventoryStatus.ON_GOING,
            center_id=2,
            user_id=4,
        ),
        Inventory(
            inventory_start_date=date(2026, 3, 10),
            inventory_end_date=date(2026, 3, 10),
            status=InventoryStatus.FINISHED,
            center_id=1,
            user_id=3,
        ),
        Inventory(
            inventory_start_date=date(2026, 8, 1),
            inventory_end_date=None,
            status=InventoryStatus.ON_GOING,
            center_id=1,
            user_id=3,
        ),
    ]

    inventory_stocks = [
        # Inventaire 1 (centre 1)
        InventoryStock(
            inventory_id=1,
            stock_id=1,
            status=InventoryStockStatus.FOUND,
            scan_id=None,
        ),
        InventoryStock(
            inventory_id=1,
            stock_id=2,
            status=InventoryStockStatus.NOT_FOUND,
            scan_id=None,
        ),
        # Inventaire 2 (centre 2)
        InventoryStock(
            inventory_id=2,
            stock_id=3,
            status=InventoryStockStatus.NOT_FOUND,
            scan_id=None,
        ),
        InventoryStock(
            inventory_id=2,
            stock_id=4,
            status=InventoryStockStatus.FOUND,
            scan_id=None,
        ),
        InventoryStock(
            inventory_id=2,
            stock_id=5,
            status=InventoryStockStatus.NOT_FOUND,
            scan_id=None,
        ),
        # Inventaire 3 (centre 1, terminé)
        InventoryStock(
            inventory_id=3,
            stock_id=1,
            status=InventoryStockStatus.FOUND,
            scan_id=None,
        ),
        InventoryStock(
            inventory_id=3,
            stock_id=2,
            status=InventoryStockStatus.FOUND,
            scan_id=None,
        ),
        # Inventaire 4 (centre 1, en cours)
        InventoryStock(
            inventory_id=4,
            stock_id=1,
            status=InventoryStockStatus.FOUND,
            scan_id=None,
        ),
        InventoryStock(
            inventory_id=4,
            stock_id=2,
            status=InventoryStockStatus.NOT_FOUND,
            scan_id=None,
        ),
        InventoryStock(
            inventory_id=4,
            stock_id=6,
            status=InventoryStockStatus.FOUND,
            scan_id=None,
        ),
        InventoryStock(
            inventory_id=4,
            stock_id=7,
            status=InventoryStockStatus.NOT_FOUND,
            scan_id=None,
        ),
    ]

    stock_events = [
        StockEvent(
            stock_id=1,
            user_id=3,
            event_type=StockEventType.AJOUT_SYSTEME,
            details="Ajout initial au système",
            event_date=date(2025, 1, 1),
        ),
        StockEvent(
            stock_id=1,
            user_id=3,
            event_type=StockEventType.PROBLEME_REPORTED,
            details="Signalé manquant lors de l'inventaire",
            event_date=date(2026, 6, 1),
        ),
        StockEvent(
            stock_id=2,
            user_id=3,
            event_type=StockEventType.AJOUT_SYSTEME,
            details="Ajout initial au système",
            event_date=date(2025, 6, 1),
        ),
        StockEvent(
            stock_id=3,
            user_id=4,
            event_type=StockEventType.AJOUT_SYSTEME,
            details="Ajout initial au système",
            event_date=date(2025, 1, 1),
        ),
        StockEvent(
            stock_id=4,
            user_id=4,
            event_type=StockEventType.TRANSFERT_RECU,
            details="Transfert reçu depuis l'entrepôt",
            event_date=date(2025, 9, 1),
        ),
        StockEvent(
            stock_id=5,
            user_id=4,
            event_type=StockEventType.AJOUT_SYSTEME,
            details="Ajout initial au système",
            event_date=date(2025, 1, 1),
        ),
    ]

    db.add_all(users)
    db.add_all(stocks)
    db.add_all(centers)
    db.add_all(center_schedules)
    db.add_all(vehicules)
    db.add_all(vehicule_documents)
    db.commit()
    db.add_all(closing_periods)
    db.commit()
    db.add_all(inventories)
    db.commit()
    db.add_all(inventory_stocks)
    db.commit()
    db.add_all(stock_events)
    db.commit()
    db.close()
    print("Seed OK ✅")
